global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'social-backend'
    static_configs:
      - targets: ['host.docker.internal:8000']  # Django dev server
    metrics_path: '/health/metrics'
    scrape_interval: 30s

  - job_name: 'social-backend-prod'
    static_configs:
      - targets: ['host.docker.internal:8002']  # Production Gunicorn
    metrics_path: '/health/metrics'
    scrape_interval: 30s