# Generated by Django 4.2.15 on 2025-08-14 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = []
