# Generated by Django 4.2.15 on 2025-08-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0003_add_connection_type"),
    ]

    operations = [
        migrations.AddField(
            model_name='socialaccount',
            name='posting_enabled',
            field=models.BooleanField(default=True, help_text="Whether this account supports API posting"),
        ),
    ]
