# Generated by Django 4.2.23 on 2025-08-15 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_add_posting_enabled_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialcomment',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='socialidea',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='socialmediafile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='socialpost',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='socialaccount',
            unique_together={('platform', 'account_id')},
        ),
        migrations.AlterUniqueTogether(
            name='socialhashtag',
            unique_together={('tag',)},
        ),
        migrations.AlterUniqueTogether(
            name='socialqueue',
            unique_together={('account', 'name')},
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='socialhashtag',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='socialqueue',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
