# Generated by Django 4.2.23 on 2025-08-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_remove_socialcomment_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='profile_picture_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
