# Generated by Django 4.2.15 on 2025-08-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0006_increase_profile_picture_url_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediafile",
            name="mime_type",
            field=models.CharField(max_length=200),
        ),
    ]
