# Generated by Django 4.2.15 on 2025-08-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0007_extend_mime_type_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediafile",
            name="file",
            field=models.FileField(max_length=500, upload_to="social_media/%Y/%m/"),
        ),
    ]
